### ISSUE TITLE
使用yolov5經常發生內存問題

### ISSUE THREAD

**Issue by s0966066980** [ycdhqzhiai/Yolov5_Tensorflow#7]
如標題,當我使用yolov5訓練時,
The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
我將batch_size設置為2一樣有這問題
但我使用pytorch版本能將batch_size設置為32
想請問您如何解決

**Comment by ycdhqzhiai** [comment]
额，很久没看git了，这个repository当时写的情况是，初步接触tf 和yolov5，正好有这个机会尝试了下，肯定漏洞百出，仅供学习使用，建议torch
